"""empty message

Revision ID: 3f3cf9d79dc7
Revises: 1cb0c928e584
Create Date: 2018-12-26 20:20:53.139596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3cf9d79dc7'
down_revision = '1cb0c928e584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'category')
    # ### end Alembic commands ###
