"""empty message

Revision ID: c7c8551fd23a
Revises: 5b89d1785d77
Create Date: 2018-12-26 11:45:08.834845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c8551fd23a'
down_revision = '5b89d1785d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('md5_hash', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'md5_hash')
    # ### end Alembic commands ###
